name: Update scores.json

on:
  schedule:
    - cron: '*/30 * * * *'  # her 30 dakikada bir çalışır (Free plan için güvenli)
  workflow_dispatch: {}      # elle başlatabilmek için

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch live & today fixtures
        env:
          API_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: |
          set -e
          BASE="https://v3.football.api-sports.io/fixtures"
          HDR="x-apisports-key: ${API_KEY}"

          # Bugünkü maçlar (İstanbul saatine göre)
          TODAY=$(curl -s -H "$HDR" "$BASE?date=$(date +%F)&timezone=Europe/Istanbul")
          # Canlı maçlar
          LIVE=$(curl -s -H "$HDR" "$BASE?live=all&timezone=Europe/Istanbul")

          echo "$TODAY" > today.json
          echo "$LIVE" > live.json

          jq -s '{
            updated_at: (now | todateiso8601),
            fixtures: (
              (.[0].response + .[1].response)
              | unique_by(.fixture.id)
              | map({
                  id: .fixture.id,
                  league: {
                    id: .league.id,
                    name: .league.name,
                    country: .league.country,
                    season: .league.season,
                    round: .league.round
                  },
                  status: {
                    short: .fixture.status.short,
                    long: .fixture.status.long,
                    elapsed: (.fixture.status.elapsed // 0)
                  },
                  datetime_utc: .fixture.date,
                  home: {
                    id: .teams.home.id,
                    name: .teams.home.name,
                    goals: (.goals.home // 0)
                  },
                  away: {
                    id: .teams.away.id,
                    name: .teams.away.name,
                    goals: (.goals.away // 0)
                  }
                })
            )
          }' today.json live.json > scores.json

      - name: Commit & push if changed
        run: |
          if ! git diff --quiet -- scores.json; then
            git config user.name "score-bot"
            git config user.email "actions@users.noreply.github.com"
            git add scores.json
            git commit -m "Update scores.json $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          else
            echo "No changes"
          fi
